services:
  api:
    image: rpg-maestro-api:latest
    container_name: rpg-maestro-api-test
    ports:
      - "8080:8000"
    env_file:
      - .env.docker
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
