services:
  # Backend API service
  - type: web
    name: rpg-maestro-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: AI21_API_KEY
        sync: false
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: SESAME_API_KEY
        sync: false
    autoDeploy: true
